CREATE OR REPLACE PROCEDURE L0_HELIOS_DEV.PUBLIC.P_L0_2N_TEST()
RETURNS VARCHAR(255)
LANGUAGE SQL
EXECUTE AS CALLER
AS 'BEGIN 

    SELECT TOP 10 * FROM L0_HELIOS.PUBLIC.L0_2N_FIXRATES;
    RETURN ''OK'';

return ''AOK''; /*POČET VLOŽENÝCH ZÁZNAMŮ*/
end';