/* 
Create simple thing
*/

CREATE OR REPLACE PROCEDURE PUBLIC.P_L0_2N_TEST()
RETURNS varchar(255)
LANGUAGE SQL
EXECUTE AS CALLER
AS 
BEGIN 

    SELECT TOP 10 * FROM L0_HELIOS.PUBLIC.L0_2N_FIXRATES;
    RETURN 'OK';

return 'AOK'; /*POČET VLOŽENÝCH ZÁZNAMŮ*/
end;
;
